### ISSUE TITLE
Support endpoints choices/options in Netbox 2.8

### ISSUE THREAD

**Issue by aruhier** [scaleway/python-netboxapi#8]
Before Netbox 2.8, enums were given through a `_choices` endpoint. Now Netbox has moved to `OPTIONS` since 2.8: https://github.com/netbox-community/netbox/issues/3416

The options are now linked to each specific endpoints, meaning that it could be attached to a mapper. 

pynetbox did it like this: https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/endpoint.py#L294

**Comment by i4networks** [comment]
I have an issue with this too. importer is not working anymore

**Comment by i4networks** [comment]
@aruhier We gave it a shot to fix it today. but we are lost in some details.
Can you help us out with an outline of the general flow and where the OPTIONS are usefull in the push?
at this moment, requesting the options works, but we dont know the actual format of the former _choices 

could you provide us a sample for /api/ipam/ip_addresses/_choices

**Comment by aruhier** [comment]
Sorry for the late answer. I don't have a version of Netbox < 2.8 running, but maybe @scaleway does?

But you have an example of usage here: https://github.com/scaleway/netbox-netprod-importer/blob/master/netbox_netprod_importer/push.py#L53
Under each "app_name" (being `/api/ipam`, `/api/dcim/`, etc.) you had an endpoint called `_choices`, that returned a dict containing ids and the list of enums you could have for it.

Example:
```
{
  "interface:mode": [
    {"label": "trunk", value: 10},
    {"label": "access", value: 20},
  ],
}
```

Now it should be pretty similar with `OPTIONS`, but it doesn't work by `app_name` anymore. The enum is now listed by the endpoint directly, and they renamed `label` to `display_name`.

**Comment by ryanmerolle** [comment]
@aruhier you can test against http://netboxdemo.com if you need to test against netbox with > 2.8.

**Comment by rinsekloek** [comment]
We do also bump into the problem that Netbox 2.8+ is not supported anymore. Can you indicatie when this will be fixed ?

**Comment by ludvik78** [comment]
We also have this issue

**Comment by jesk78** [comment]
dead?

**Comment by Simperdy** [comment]
I hope someone can fix this

**Comment by GangstaPirates** [comment]
Also looking for a fix for this.

**Comment by axelolmos** [comment]
For people searching for answers netbox-netprod-importer does not work with netbox 2.10.

https://YOURNETBOX/api/dcim/_choices

is called by the importer and the _choices API was deprecated.

It will return an error message:
ERROR: netbox_importer: Error when polling device YOURNETBOX: 404 Client Error: Not Found for url: https://YOURNETBOX/api/dcim/_choices/?limit=50

As a result, anyone running recent versions of netbox attempting to use netbox-netprod-importer 0.3.3 will not be able to import devices.

**Comment by gitnetofr** [comment]
Hi, 

Any news about this issue?

**Comment by brianpr** [comment]
I have the same problem

I updated netbox to the latest version and also tried updating "pip install git + https: //github.com/scaleway/python-netboxapi.git"

but nothing...

any ideas?
